version: "3.9"

services:
  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: library-app:v1
    container_name: library-app
    environment:
      - MONGO_URI=mongodb://library-db:27017/libraryDB
      - DB_NAME=libraryDB
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - library-db
    restart: always

  library-db:
    image: mongo:latest
    container_name: library-db
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    restart: always
