apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
  namespace: library-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library-app
        image: sreeja026/libraryimage:v1
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://rootuser:rootpassword@mongo-service:27017/libraryDB?authSource=admin"
        - name: DB_NAME
          value: "libraryDB"
        - name: PORT
          value: "3000"
